-- ===================================================================
-- MovieVerse Sample Seed Data Script (18+ Movies + Seed Users)
-- ===================================================================

-- 1. Insert Demo Users (Password: password123 with BCrypt hash)
INSERT INTO users (id, name, email, password, role) VALUES 
(1, 'Alex Johnson', 'alex@movieverse.com', '$2a$10$w0JbYFz7c.yv61lW8w1f4O.RjS2eZc0XvN2K1E8F2P3Q4R5S6T7U8', 'USER'),
(2, 'Demo User', 'demo@movieverse.com', '$2a$10$w0JbYFz7c.yv61lW8w1f4O.RjS2eZc0XvN2K1E8F2P3Q4R5S6T7U8', 'USER')
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- 2. Insert Sample Movies with Authentic OMDb Poster URLs and Official Trailers
INSERT INTO movies (id, title, description, genre, rating, release_date, duration, language, country, director, cast, poster_url, backdrop_url, trailer_url, is_popular, is_latest, is_trending) VALUES 
(1, 'Avengers: Endgame', 'After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos actions and restore balance to the cosmos.', 'Action, Sci-Fi', 8.4, '2019-04-26', '181 min', 'English', 'United States', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX1200.jpg', 'https://www.youtube.com/embed/TcMBFSGVi1c', true, false, true),
(2, 'Interstellar', 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft to find a new habitable planet for humanity.', 'Sci-Fi, Drama', 8.7, '2014-11-07', '169 min', 'English', 'United States', 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine', 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/zSWdZVtXT7E', true, false, true),
(3, 'Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a C.E.O., but his past threatens his mission.', 'Sci-Fi, Action, Thriller', 8.8, '2010-07-16', '148 min', 'English', 'United States', 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX1200.jpg', 'https://www.youtube.com/embed/YoHD9XEInc0', true, false, true),
(4, 'The Dark Knight', 'When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.', 'Action, Crime, Drama', 9.0, '2008-07-18', '152 min', 'English', 'United States', 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX1200.jpg', 'https://www.youtube.com/embed/EXeTwQWrcwY', true, false, true),
(5, 'Spider-Man: No Way Home', 'With Spider-Man identity revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other multiverses appear.', 'Action, Sci-Fi, Adventure', 8.2, '2021-12-17', '148 min', 'English', 'United States', 'Jon Watts', 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Willem Dafoe', 'https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/JfVOs4VSpmA', true, false, false),
(6, 'Avatar: The Way of Water', 'Jake Sully lives with his newfound family on the moon Pandora. Once a familiar threat returns, Jake must work with Neytiri and the Na vi to protect their home.', 'Sci-Fi, Action, Adventure', 7.6, '2022-12-16', '192 min', 'English', 'United States', 'James Cameron', 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Kate Winslet', 'https://m.media-amazon.com/images/M/MV5BNWI0Y2NkOWEtMmM2OC00MjQ3LWI1YzItZGQxYzQ3NzI4NWZmXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNWI0Y2NkOWEtMmM2OC00MjQ3LWI1YzItZGQxYzQ3NzI4NWZmXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/d9MyW72ELq0', false, true, true),
(7, 'Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic during its 1912 maiden voyage.', 'Drama, Romance', 7.9, '1997-12-19', '194 min', 'English', 'United States', 'James Cameron', 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates', 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/2e-eXJ6HgkQ', true, false, false),
(8, 'Jurassic Park', 'A pragmatic paleontologist touring an almost complete theme park on an island is tasked with protecting kids after cloned dinosaurs run loose.', 'Sci-Fi, Thriller, Adventure', 8.2, '1993-06-11', '127 min', 'English', 'United States', 'Steven Spielberg', 'Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough', 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX1200.jpg', 'https://www.youtube.com/embed/QWBKEmWWL38', false, false, true),
(9, 'The Matrix', 'When a computer hacker learns about the true nature of his reality, he joins a rebellion against the machines controlling humanity.', 'Sci-Fi, Action', 8.7, '1999-03-31', '136 min', 'English', 'United States', 'Lana Wachowski, Lilly Wachowski', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving', 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/vKQi3bBA1y8', true, false, true),
(10, 'Dangal', 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games.', 'Drama, Biography, Sport', 8.3, '2016-12-23', '161 min', 'Hindi', 'India', 'Nitesh Tiwari', 'Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar', 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX1200.jpg', 'https://www.youtube.com/embed/x_7YlGv9u1g', true, false, true),
(11, '3 Idiots', 'Two friends search for their long lost companion and recall memories of their college days and the friend who inspired them to think outside the box.', 'Comedy, Drama', 8.4, '2009-12-25', '170 min', 'Hindi', 'India', 'Rajkumar Hirani', 'Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor', 'https://m.media-amazon.com/images/M/MV5BNzc4ZWQ3NmYtODE0Ny00YTQ4LTlkZWItNTBkMGQ0MmUwMmJlXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNzc4ZWQ3NmYtODE0Ny00YTQ4LTlkZWItNTBkMGQ0MmUwMmJlXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/K0eDlFX9GMc', true, false, false),
(12, 'Baahubali 2: The Conclusion', 'When Shiva learns about his heritage, he begins to look for answers while past events in the Mahishmati Kingdom unfold.', 'Action, Drama, Fantasy', 8.2, '2017-04-28', '167 min', 'Telugu, Hindi', 'India', 'S.S. Rajamouli', 'Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah Bhatia', 'https://m.media-amazon.com/images/M/MV5BNTRhYTlhZTgtYmMyYy00NWI4LTk4MzItOWM2YjBmYTg2OTI2XkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNTRhYTlhZTgtYmMyYy00NWI4LTk4MzItOWM2YjBmYTg2OTI2XkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/G62HrubdD6o', true, false, true),
(13, 'K.G.F: Chapter 2', 'In the blood-soaked Kolar Gold Fields, Rocky strikes fear into his foes while battling enemies from all sides for undisputed supremacy.', 'Action, Crime, Drama', 8.3, '2022-04-14', '168 min', 'Kannada, Hindi', 'India', 'Prashanth Neel', 'Yash, Sanjay Dutt, Raveena Tandon, Srinidhi Shetty', 'https://m.media-amazon.com/images/M/MV5BZmQzZjVkZTUtYjI4ZC00ZDJmLWI0ZDUtZTFmMGM1Mzc5ZjIyXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BZmQzZjVkZTUtYjI4ZC00ZDJmLWI0ZDUtZTFmMGM1Mzc5ZjIyXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/JKa05nyUmuQ', true, true, true),
(14, 'RRR', 'A fearless revolutionary and an officer in the British force decide to join forces and chart out an inspirational path of freedom in 1920s India.', 'Action, Drama', 7.8, '2022-03-25', '187 min', 'Telugu, Hindi', 'India', 'S.S. Rajamouli', 'N.T. Rama Rao Jr., Ram Charan, Ajay Devgn, Alia Bhatt', 'https://m.media-amazon.com/images/M/MV5BNWMwODYyMjQtMTczMi00NTQ1LWFkYjItMGJhMWRkY2E3NDAyXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNWMwODYyMjQtMTczMi00NTQ1LWFkYjItMGJhMWRkY2E3NDAyXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/f_vbAtFSEc0', true, true, true),
(15, 'Pushpa: The Rise', 'Pushpa Raj, a coolie, volunteers to smuggle red sanders and quickly rises through the syndicate ranks through sheer grit.', 'Action, Crime, Thriller', 7.6, '2021-12-17', '179 min', 'Telugu, Hindi', 'India', 'Sukumar', 'Allu Arjun, Rashmika Mandanna, Fahadh Faasil', 'https://m.media-amazon.com/images/M/MV5BOWE4YWEyNjYtMWFiNC00M2IzLWE3ZGMtMjQ0ZGEyOWI1YjAzXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BOWE4YWEyNjYtMWFiNC00M2IzLWE3ZGMtMjQ0ZGEyOWI1YjAzXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/pKctjlpbqpA', false, true, true),
(16, 'Spirited Away', 'During a move to the suburbs, a 10-year-old girl wanders into a world ruled by spirits, gods, and witches.', 'Animation, Adventure, Fantasy', 8.6, '2001-07-20', '125 min', 'Japanese', 'Japan', 'Hayao Miyazaki', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki', 'https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/ByXuk9QqQkk', true, false, false),
(17, 'The Conjuring', 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.', 'Horror, Thriller, Mystery', 7.5, '2013-07-19', '112 min', 'English', 'United States', 'James Wan', 'Patrick Wilson, Vera Farmiga, Ron Livingston, Lili Taylor', 'https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX1200.jpg', 'https://www.youtube.com/embed/k10ETZ41q5o', false, false, false),
(18, 'La La Land', 'While navigating their careers in Los Angeles, a jazz pianist and an aspiring actress fall in love while pursuing their passions.', 'Comedy, Drama, Romance', 8.0, '2016-12-09', '128 min', 'English', 'United States', 'Damien Chazelle', 'Ryan Gosling, Emma Stone, John Legend, J.K. Simmons', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX1200.jpg', 'https://www.youtube.com/embed/0pdqf4P9MB8', true, false, false),
(19, 'Oppenheimer', 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.', 'Drama, Biography, History', 8.9, '2023-07-21', '180 min', 'English, German', 'United States', 'Christopher Nolan', 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Florence Pugh', 'https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/uYPbbksJxIg', true, true, true),
(20, 'Dune: Part Two', 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', 'Sci-Fi, Action, Adventure', 8.6, '2024-03-01', '166 min', 'English', 'United States', 'Denis Villeneuve', 'Timothee Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem, Austin Butler', 'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_SX600.jpg', 'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_SX1200.jpg', 'https://www.youtube.com/embed/Way9Dexny3w', true, true, true)
ON DUPLICATE KEY UPDATE title=VALUES(title);

-- 3. Insert Sample Favourites
INSERT INTO favourites (id, user_id, movie_id) VALUES
(1, 1, 1),
(2, 1, 2),
(3, 1, 4),
(4, 2, 3),
(5, 2, 10)
ON DUPLICATE KEY UPDATE movie_id=VALUES(movie_id);
